package de.hsaugsburg.bpap.ss23.sellyourleftovers;

import de.hsaugsburg.bpap.ss23.sellyourleftovers.model.Category;
import de.hsaugsburg.bpap.ss23.sellyourleftovers.model.Product;
import de.hsaugsburg.bpap.ss23.sellyourleftovers.model.User;
import de.hsaugsburg.bpap.ss23.sellyourleftovers.repository.CategoryRepository;
import de.hsaugsburg.bpap.ss23.sellyourleftovers.repository.ProductRepository;
import de.hsaugsburg.bpap.ss23.sellyourleftovers.repository.UserRepository;
import lombok.RequiredArgsConstructor;
import org.springframework.boot.CommandLineRunner;
import org.springframework.security.crypto.password.PasswordEncoder;
import org.springframework.stereotype.Component;

import java.math.BigDecimal;
import java.util.ArrayList;
import java.util.List;

/**
 * This initializes the test data (e.g. test users, products, categories, etc.).
 */
@Component
@RequiredArgsConstructor
public class DataInitializer implements CommandLineRunner {

    private final CategoryRepository categoryRepository;
    private final ProductRepository productRepository;
    private final UserRepository userRepository;
    private final PasswordEncoder passwordEncoder;

    @Override
    public void run(String... args) throws Exception {

        // Categories
        Category beer = new Category(1L, Category.CategoryType.BEER, "Bier");
        Category wine = new Category(2L, Category.CategoryType.WINE, "Wein");
        Category spirits = new Category(3L, Category.CategoryType.SPIRITS, "Spirituosen");
        Category nonAlcoholic = new Category(4L, Category.CategoryType.NONALCOHOLIC, "Softgetränke");

        categoryRepository.save(beer);
        categoryRepository.save(wine);
        categoryRepository.save(spirits);
        categoryRepository.save(nonAlcoholic);

        // Products
        productRepository.save(new Product(1L, "Wodka Gorbatschow 200ml", "https://iili.io/HwltObI.jpg", "Der Wodka Gorbatschow ist ein hochwertiger Wodka aus Deutschland, der aus feinstem Weizen hergestellt wird. Er zeichnet sich durch sein mildes und zugleich würziges Aroma aus. Durch seine vielseitige Verwendungsmöglichkeiten eignet er sich perfekt zum Mixen von Cocktails oder als Begleiter zu einem eleganten Dinner. Ein absoluter Klassiker unter den Wodkas!", new BigDecimal(3), true, Category.CategoryType.SPIRITS));
        productRepository.save(new Product(2L, "Ramero Rum Blanco 3x 500ml", "https://iili.io/Hwltkxt.webp", "Der Ramero Rum Blanco ist ein erfrischender Rum aus der Karibik, der aus besten Zuckerrohrmelassen hergestellt wird. Er besticht durch seine klare, kristalline Farbe und sein leicht süßes Aroma mit einem Hauch von Vanille und tropischen Früchten. Der Rum eignet sich hervorragend zum Mixen von Cocktails oder als Basis für erfrischende Longdrinks. Ein idealer Begleiter für warme Sommerabende oder entspannte Stunden auf der Terrasse.", new BigDecimal(49.99), true, Category.CategoryType.SPIRITS));
        productRepository.save(new Product(3L, "Sprizzero Bitterorange 10x 300ml", "https://iili.io/Hwlt8sn.jpg", "Der Sprizzero Bitterorange ist ein erfrischendes und belebendes Getränk, das aus natürlichen Zutaten hergestellt wird. Er vereint den herben Geschmack von Bitterorangen mit einer angenehmen Süße und einem Hauch von Kräutern. Der Sprizzero Bitterorange eignet sich perfekt als Aperitif oder als Begleiter zu einem entspannten Abend mit Freunden. Ein unverwechselbares Geschmackserlebnis, das Sie sich nicht entgehen lassen sollten.", new BigDecimal(12.00), true, Category.CategoryType.SPIRITS));
        productRepository.save(new Product(4L, "Tequila Herencia de Plata 700ml", "https://iili.io/HwltUfs.jpg", "Herencia de Plata ist ein preisgekrönter Tequila aus 100% blauer Agave, der in Mexiko produziert wird. Er überzeugt durch sein intensives Aroma mit einem Hauch von Zimt und Vanille und seinen ausgewogenen Geschmack mit einer leichten Schärfe. Der Tequila eignet sich hervorragend zum Genießen pur oder als Basis für Tequila-Cocktails. Herencia de Plata ist ein Premium-Tequila, der für höchste Qualität und Handwerkskunst steht.", new BigDecimal(23.00), true, Category.CategoryType.SPIRITS));
        productRepository.save(new Product(5L, "Steiger Whisky 700ml", "https://iili.io/Hwltrgf.jpg", "Der Steiger Whisky ist ein hochwertiger Single Malt Whisky aus Österreich, der aus erlesenen Gerstenmalzen und kristallklarem Bergquellwasser destilliert wird. Er reift mindestens 3 Jahre in Eichenfässern und überzeugt durch sein intensives Aroma mit einer angenehmen Rauchnote und einer subtilen Süße. Der Steiger Whisky eignet sich perfekt als Geschenk für Whiskyliebhaber oder zum Genießen in gemütlicher Atmosphäre. Ein authentischer Whisky, der für Qualität und Genuss auf höchstem Niveau steht.", new BigDecimal(25), true, Category.CategoryType.SPIRITS));
        productRepository.save(new Product(6L, "Coca Cola 335ml", "https://iili.io/Hwl4H5F.jpg", "Coca Cola ist ein erfrischendes Softgetränk, das seit 1886 weltweit bekannt und beliebt ist. Es wird aus natürlichen Zutaten wie Zucker, Koffein und natürlichen Aromen hergestellt und hat einen unverwechselbaren Geschmack. Coca Cola ist vielseitig einsetzbar und eignet sich hervorragend als Durstlöscher oder als Basis für leckere Cocktailkreationen. Ein Klassiker unter den Softdrinks, der unverwechselbar erfrischend schmeckt.", new BigDecimal(2), true, Category.CategoryType.NONALCOHOLIC));
        productRepository.save(new Product(7L, "Dr Pepper Cherry 300ml", "https://iili.io/Hwl4dba.jpg", "Dr Pepper Cherry ist ein erfrischendes Softgetränk mit einem unverwechselbaren Geschmack. Die Kombination aus Dr Pepper und Kirschgeschmack macht es zu einem besonderen Geschmackserlebnis. Es wird aus natürlichen Zutaten hergestellt und ist koffeinhaltig. Dr Pepper Cherry eignet sich perfekt als Durstlöscher oder als Begleiter zu einem gemütlichen Filmabend. Ein erfrischender Softdrink, der nicht nur Kirschfans begeistert.", new BigDecimal(1.99), true, Category.CategoryType.NONALCOHOLIC));
        productRepository.save(new Product(8L, "Fanta Pineapple 300ml", "https://iili.io/Hwl49J1.jpg", "Fanta Pineapple ist ein erfrischender Softdrink mit exotischem Ananas-Geschmack. Das fruchtige Getränk wird aus natürlichen Zutaten hergestellt und enthält keine künstlichen Farbstoffe. Fanta Pineapple ist koffeinfrei und eignet sich perfekt als erfrischende Abwechslung an warmen Tagen oder als Basis für leckere Cocktailkreationen. Ein erfrischender Softdrink, der durch seinen exotischen Geschmack ein tropisches Flair versprüht.", new BigDecimal(2), true, Category.CategoryType.NONALCOHOLIC));
        productRepository.save(new Product(9L, "Monster Energy 500ml", "https://iili.io/HOCvRvn.png", "Monster Energy ist ein erfrischendes Energy-Drink mit einem intensiven Geschmack und einem hohen Koffeingehalt. Das Getränk wird aus natürlichen Zutaten wie Taurin, B-Vitaminen und Guarana hergestellt und gibt einen schnellen Energiekick. Monster Energy eignet sich perfekt für lange Partynächte, anstrengende Workouts oder um in stressigen Situationen wach und konzentriert zu bleiben. Ein kraftvoller Energy-Drink, der für seine Wirksamkeit und den einzigartigen Geschmack bekannt ist.", new BigDecimal(2.50), true, Category.CategoryType.NONALCOHOLIC));
        productRepository.save(new Product(10L, "Red Bull 300ml", "https://iili.io/Hwl4JOg.jpg", "Red Bull ist ein bekannter Energy-Drink mit einem einzigartigen Geschmack und einer hohen Konzentration an Koffein, Taurin und B-Vitaminen. Er gibt schnell und langanhaltend Energie und erhöht die Konzentration und Leistungsfähigkeit. Red Bull eignet sich perfekt für lange Arbeitstage, lange Autofahrten oder intensive Sporteinheiten. Ein Energy-Drink, der weltweit bekannt ist und für seine belebende Wirkung und seinen unverwechselbaren Geschmack geschätzt wird.", new BigDecimal(2.99), true, Category.CategoryType.NONALCOHOLIC));
        productRepository.save(new Product(11L, "Sprite 12x 250ml", "https://iili.io/Hwl4FWv.jpg", "Sprite ist ein erfrischender Softdrink mit einem leichten, zitrusartigen Geschmack und einem klaren Aussehen. Er wird aus natürlichen Zutaten wie Zucker, Zitronen- und Limettenaromen hergestellt und ist koffeinfrei. Sprite eignet sich perfekt als Durstlöscher oder als Begleiter zu leichten Mahlzeiten oder Snacks. Ein erfrischender Softdrink, der durch seinen leichten Geschmack und die Spritzigkeit überzeugt.", new BigDecimal(10), true, Category.CategoryType.NONALCOHOLIC));
        productRepository.save(new Product(12L, "Augustiner Helles 20x 500ml", "https://iili.io/Hwl8hjR.jpg", "Augustiner Helles ist ein untergäriges Bier aus München, das sich durch seinen leichten und erfrischenden Geschmack auszeichnet. Das Bier wird nach dem bayerischen Reinheitsgebot gebraut und besteht aus Wasser, Malz und Hopfen. Es hat einen Alkoholgehalt von 5,2% und eine goldene Farbe. Augustiner Helles ist ein klassisches Münchner Bier, das sich perfekt als Begleiter zu deftigen Speisen wie Schweinshaxe oder Leberknödel eignet. Ein erfrischendes Bier, das durch seine milde Bitternote und seinen angenehmen Abgang überzeugt.", new BigDecimal(17.99), true, Category.CategoryType.BEER));
        productRepository.save(new Product(13L, "Chiemseer Helles 20x 500ml", "https://iili.io/Hwl8E3F.jpg", "Chiemseer Helles ist ein süddeutsches Bier aus der Region rund um den Chiemsee. Es wird nach dem bayerischen Reinheitsgebot gebraut und besteht aus Wasser, Malz und Hopfen. Das Bier hat eine helle Farbe und einen milden Geschmack mit einer leichten Hopfennote. Chiemseer Helles ist ein erfrischendes Bier, das sich perfekt als Durstlöscher an warmen Tagen eignet und auch zu leichten Gerichten wie Salaten oder Fisch passt. Ein traditionelles bayerisches Bier, das durch seine Ausgewogenheit und seinen angenehmen Abgang überzeugt.", new BigDecimal(15.99), true, Category.CategoryType.BEER));
        productRepository.save(new Product(14L, "Paulaner Hefe-Weissbier Dose 500ml", "https://iili.io/Hwl8Mva.jpg", "Paulaner Weissbier ist ein bekanntes Bier aus Bayern und wird in zwei Varianten angeboten: alkoholfrei und mit Alkohol. Das alkoholfreie Bier wird aus hochwertigen Zutaten hergestellt und hat einen erfrischenden Geschmack mit einem fruchtigen Aroma von Bananen und Nelken. Es ist eine ideale Wahl für alle, die auf Alkohol verzichten möchten. Die Version mit Alkohol hat einen Alkoholgehalt von 5,5% und ist ein vollmundiges, leicht süßliches Bier mit einem fruchtigen Geschmack und einem Hauch von Gewürzen. Beide Varianten von Paulaner Weissbier zeichnen sich durch ihre hohe Qualität und ihren unverwechselbaren Geschmack aus.", new BigDecimal(0.99), true, Category.CategoryType.BEER));
        productRepository.save(new Product(15L, "Münchner Helles Fass 5l", "https://iili.io/Hwl8VyJ.jpg", "Münchner Helles ist ein untergäriges Bier, das seinen Ursprung in der bayerischen Landeshauptstadt hat. Es hat eine helle Farbe und einen erfrischenden Geschmack mit einem ausgewogenen Verhältnis von Malz- und Hopfenaromen. Der Alkoholgehalt liegt typischerweise zwischen 4,5% und 5,5%. Münchner Helles ist ein traditionelles Bier, das gerne zu bayerischen Spezialitäten wie Brezen und Weißwurst getrunken wird. Es ist auch eine beliebte Wahl für alle, die ein leichtes, erfrischendes Bier suchen.", new BigDecimal(10.99), true, Category.CategoryType.BEER));
        productRepository.save(new Product(16L, "Paulaner Hefe-Weissbier alkoholfrei 20x 500ml", "https://iili.io/Hwl8jQp.jpg", "Paulaner Weissbier ist ein bekanntes Bier aus Bayern und wird in zwei Varianten angeboten: alkoholfrei und mit Alkohol. Das alkoholfreie Bier wird aus hochwertigen Zutaten hergestellt und hat einen erfrischenden Geschmack mit einem fruchtigen Aroma von Bananen und Nelken. Es ist eine ideale Wahl für alle, die auf Alkohol verzichten möchten. Die Version mit Alkohol hat einen Alkoholgehalt von 5,5% und ist ein vollmundiges, leicht süßliches Bier mit einem fruchtigen Geschmack und einem Hauch von Gewürzen. Beide Varianten von Paulaner Weissbier zeichnen sich durch ihre hohe Qualität und ihren unverwechselbaren Geschmack aus.", new BigDecimal(9.99), true, Category.CategoryType.BEER));
        productRepository.save(new Product(17L, "Riegele Commerzienrat 20x 500ml", "https://iili.io/Hwl8OGI.jpg", "Riegele Commerzienrat ist ein Bier aus der renommierten Augsburger Brauerei Riegele, das sich durch seinen kräftigen Geschmack und seine dunkle Farbe auszeichnet. Es wird aus einer speziellen Mischung aus dunklem Malz und Hopfen gebraut und hat einen Alkoholgehalt von 7,5%. Das Bier hat einen vollmundigen Geschmack mit Aromen von Kaffee und Schokolade und eignet sich perfekt als Begleiter zu kräftigen Gerichten wie Rinderbraten oder Wild. ", new BigDecimal(18.99), true, Category.CategoryType.BEER));
        productRepository.save(new Product(18L, "Rothaus Tannenzäpfle 20x 333ml", "https://iili.io/Hwl8e4t.jpg", "Rothaus Tannenzäpfle ist ein beliebtes Bier aus dem Schwarzwald, das sich durch seinen erfrischenden Geschmack und seine klare, goldene Farbe auszeichnet. Das Bier wird aus ausgewählten Hopfen und Malzsorten gebraut und hat einen Alkoholgehalt von 5,1%. Es hat ein ausgewogenes Verhältnis von Süße und Bitterkeit und eignet sich perfekt als Begleiter zu herzhaften Gerichten wie gegrilltem Fleisch oder deftigem Käse. Rothaus Tannenzäpfle ist ein traditionelles Bier, das durch seine hohe Qualität und seinen unverwechselbaren Geschmack überzeugt.", new BigDecimal(15.00), true, Category.CategoryType.BEER));
        productRepository.save(new Product(19L, "Bree Rosé Pinot Noir 6x 700ml", "https://iili.io/Hwl6e6l.jpg", "Bree Rosé ist ein erfrischender Perlwein aus Spanien mit einem fruchtigen Geschmack und einem zarten Rosé-Ton. Er wird aus sorgfältig ausgewählten Weintrauben hergestellt und hat einen Alkoholgehalt von 8,5%. Bree Rosé eignet sich perfekt als Begleiter zu leichten Mahlzeiten, bei Picknicks oder als Aperitif. Ein erfrischender Perlwein, der durch seine feinen Aromen und seine Spritzigkeit überzeugt.", new BigDecimal(17.99), true, Category.CategoryType.WINE));
        productRepository.save(new Product(20L, "Promessa Rosé 6x 700ml", "https://iili.io/Hwl6Nnf.jpg", "Promessa Rosé ist ein fruchtiger und erfrischender Roséwein aus Portugal mit einem zarten Aroma von roten Beeren und Kirschen. Er wird aus ausgewählten Trauben der Rebsorte Touriga Nacional und Tinta Roriz hergestellt und hat einen Alkoholgehalt von 12,5%. Promessa Rosé eignet sich perfekt als Begleiter zu leichten Gerichten, Fisch und Meeresfrüchten oder als Aperitif. Ein erfrischender Roséwein, der durch seine ausgewogene Säure und sein angenehmes Bouquet überzeugt.", new BigDecimal(15.99), true, Category.CategoryType.WINE));
        productRepository.save(new Product(21L, "Samtrot Süß und Fruchtig Rotwein 6x 700ml", "https://iili.io/Hwl6S87.png", "Samtrot süß ist ein aromatischer Rotwein aus Württemberg mit einem vollen Geschmack und einem tiefroten Farbton. Er wird aus der Rebsorte Samtrot hergestellt und hat einen Alkoholgehalt von 10,5%. Samtrot süß eignet sich perfekt als Begleiter zu kräftigen Speisen wie Wild, Lamm oder würzigem Käse. Ein vollmundiger Rotwein, der durch seine süße Note und sein angenehmes Bouquet überzeugt.", new BigDecimal(16.99), true, Category.CategoryType.WINE));
        productRepository.save(new Product(22L, "Süß und Fruchtig Mix 6x 700ml", "https://iili.io/Hwl6rue.png", "\"Süß und fruchtig\" ist eine Bezeichnung für Weine, die durch ihre süße Note und fruchtigen Aromen überzeugen. Diese Weine können sowohl Weißweine als auch Rotweine umfassen und werden oft aus spät gelesenen Trauben hergestellt. Sie eignen sich perfekt als Aperitif oder Begleiter zu Desserts und können auch als leichter Durstlöscher an heißen Tagen dienen. \"Süß und fruchtig\" Weine sind beliebt bei Weinliebhabern, die ein süßeres Geschmacksprofil bevorzugen.", new BigDecimal(16.99), true, Category.CategoryType.WINE));
        productRepository.save(new Product(22L, "Württemberg Qualitätswein rot 6x 700ml", "https://iili.io/Hwl66Zb.png", "Württemberg Qualitätswein Rot ist ein Rotwein aus der Region Württemberg in Süddeutschland, der aus ausgewählten roten Trauben hergestellt wird. Der Wein zeichnet sich durch sein tiefes Rot und seinen vollen Geschmack aus, der von Aromen von dunklen Beeren und Gewürzen geprägt ist. Württemberg Qualitätswein Rot eignet sich perfekt als Begleiter zu kräftigen Fleischgerichten oder würzigem Käse. Ein qualitativ hochwertiger Rotwein aus einer renommierten Weinregion, der durch seine Aromenvielfalt und seine Tanninstruktur überzeugt.", new BigDecimal(19.99), true, Category.CategoryType.WINE));

        // Test users for debugging
        userRepository.save(new User(1L, "test", "test", "test@test.de", passwordEncoder.encode("test"), null, new ArrayList<>(), new ArrayList<>(), new ArrayList<>()));
        userRepository.save(new User(1L, "Andreas", "Schmid", "schmidandreas.ul@gmail.com", passwordEncoder.encode("test"), null, new ArrayList<>(), new ArrayList<>(), new ArrayList<>()));

        // Test user only for testing the api endpoints
        userRepository.save(new User(2L, "test", "test", "test@test.com", passwordEncoder.encode("test"), null, new ArrayList<>(), new ArrayList<>(List.of(productRepository.findProductById(22L))), new ArrayList<>(List.of(productRepository.findProductById(1L)))));
    }
}